#!/bin/sh

# robustly figure out the real path of this script
case "$OSTYPE" in
  darwin*)  SCRIPTPATH=$( dirname $(readlink $0 || echo ".") ) ;;
  *)        SCRIPTPATH=$( dirname $(readlink -f $0) ) ;;
esac

set -xe
sudo openconnect vpn.ucl.ac.uk --csd-wrapper "$SCRIPTPATH/csd-wrapper.sh"
